name: "DEBUG: Mock Benchmark Trigger"

on:
  workflow_dispatch:
    inputs:
      mock_image:
        description: 'Image name to test'
        required: true
        default: 'ghcr.io/eaexist/subscription-killer-api:9aa1b6698762d378893a4d40ff4bb5c8f587cfd3'

jobs:
  send-dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Send Repository Dispatch to Self
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/dispatches \
            -d '{
              "event_type": "new_build",
              "client_payload": {
                "image_name": "${{ github.event.inputs.mock_image }}"
              }
            }'